#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-curator
Version  : 2.6.0
Release  : 6
URL      : https://github.com/apache/curator/archive/apache-curator-2.6.0.tar.gz
Source0  : https://github.com/apache/curator/archive/apache-curator-2.6.0.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/curator/apache-curator/2.6.0/apache-curator-2.6.0.pom
Source2  : https://repo1.maven.org/maven2/org/apache/curator/apache-curator/2.12.0/apache-curator-2.12.0.pom
Source3  : https://repo1.maven.org/maven2/org/apache/curator/apache-curator/2.7.1/apache-curator-2.7.1.pom
Source4  : https://repo1.maven.org/maven2/org/apache/curator/curator-client/2.12.0/curator-client-2.12.0.jar
Source5  : https://repo1.maven.org/maven2/org/apache/curator/curator-client/2.12.0/curator-client-2.12.0.pom
Source6  : https://repo1.maven.org/maven2/org/apache/curator/curator-client/2.6.0/curator-client-2.6.0.jar
Source7  : https://repo1.maven.org/maven2/org/apache/curator/curator-client/2.6.0/curator-client-2.6.0.jar
Source8  : https://repo1.maven.org/maven2/org/apache/curator/curator-client/2.6.0/curator-client-2.6.0.pom
Source9  : https://repo1.maven.org/maven2/org/apache/curator/curator-client/2.6.0/curator-client-2.6.0.pom
Source10  : https://repo1.maven.org/maven2/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.jar
Source11  : https://repo1.maven.org/maven2/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.pom
Source12  : https://repo1.maven.org/maven2/org/apache/curator/curator-framework/2.12.0/curator-framework-2.12.0.jar
Source13  : https://repo1.maven.org/maven2/org/apache/curator/curator-framework/2.12.0/curator-framework-2.12.0.pom
Source14  : https://repo1.maven.org/maven2/org/apache/curator/curator-framework/2.6.0/curator-framework-2.6.0.jar
Source15  : https://repo1.maven.org/maven2/org/apache/curator/curator-framework/2.6.0/curator-framework-2.6.0.pom
Source16  : https://repo1.maven.org/maven2/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.jar
Source17  : https://repo1.maven.org/maven2/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.pom
Source18  : https://repo1.maven.org/maven2/org/apache/curator/curator-recipes/2.12.0/curator-recipes-2.12.0.jar
Source19  : https://repo1.maven.org/maven2/org/apache/curator/curator-recipes/2.12.0/curator-recipes-2.12.0.pom
Source20  : https://repo1.maven.org/maven2/org/apache/curator/curator-recipes/2.6.0/curator-recipes-2.6.0.jar
Source21  : https://repo1.maven.org/maven2/org/apache/curator/curator-recipes/2.6.0/curator-recipes-2.6.0.pom
Source22  : https://repo1.maven.org/maven2/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.jar
Source23  : https://repo1.maven.org/maven2/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.pom
Source24  : https://repo1.maven.org/maven2/org/apache/curator/curator-test/2.12.0/curator-test-2.12.0.jar
Source25  : https://repo1.maven.org/maven2/org/apache/curator/curator-test/2.12.0/curator-test-2.12.0.pom
Source26  : https://repo1.maven.org/maven2/org/apache/curator/curator-test/2.6.0/curator-test-2.6.0.jar
Source27  : https://repo1.maven.org/maven2/org/apache/curator/curator-test/2.6.0/curator-test-2.6.0.pom
Source28  : https://repo1.maven.org/maven2/org/apache/curator/curator-test/2.7.1/curator-test-2.7.1.jar
Source29  : https://repo1.maven.org/maven2/org/apache/curator/curator-test/2.7.1/curator-test-2.7.1.jar
Source30  : https://repo1.maven.org/maven2/org/apache/curator/curator-test/2.7.1/curator-test-2.7.1.pom
Source31  : https://repo1.maven.org/maven2/org/apache/curator/curator-test/2.7.1/curator-test-2.7.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-curator-data = %{version}-%{release}
Requires: mvn-curator-license = %{version}-%{release}

%description
Apache Curator
--------------
Curator is a set of Java libraries that make using Apache ZooKeeper much easier.

%package data
Summary: data components for the mvn-curator package.
Group: Data

%description data
data components for the mvn-curator package.


%package license
Summary: license components for the mvn-curator package.
Group: Default

%description license
license components for the mvn-curator package.


%prep
%setup -q -n curator-apache-curator-2.6.0

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-curator
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-curator/LICENSE
cp curator-client/LICENSE %{buildroot}/usr/share/package-licenses/mvn-curator/curator-client_LICENSE
cp curator-examples/LICENSE %{buildroot}/usr/share/package-licenses/mvn-curator/curator-examples_LICENSE
cp curator-framework/LICENSE %{buildroot}/usr/share/package-licenses/mvn-curator/curator-framework_LICENSE
cp curator-recipes/LICENSE %{buildroot}/usr/share/package-licenses/mvn-curator/curator-recipes_LICENSE
cp curator-test/LICENSE %{buildroot}/usr/share/package-licenses/mvn-curator/curator-test_LICENSE
cp curator-x-discovery-server/LICENSE %{buildroot}/usr/share/package-licenses/mvn-curator/curator-x-discovery-server_LICENSE
cp curator-x-discovery/LICENSE %{buildroot}/usr/share/package-licenses/mvn-curator/curator-x-discovery_LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/apache-curator/2.6.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/apache-curator/2.6.0/apache-curator-2.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/apache-curator/2.12.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/apache-curator/2.12.0/apache-curator-2.12.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/apache-curator/2.7.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/apache-curator/2.7.1/apache-curator-2.7.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.12.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.12.0/curator-client-2.12.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.12.0
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.12.0/curator-client-2.12.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.6.0
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.6.0/curator-client-2.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.6.0
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.6.0/curator-client-2.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.6.0
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.6.0/curator-client-2.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.6.0
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.6.0/curator-client-2.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.7.1
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.7.1
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.12.0
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.12.0/curator-framework-2.12.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.12.0
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.12.0/curator-framework-2.12.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.6.0
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.6.0/curator-framework-2.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.6.0
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.6.0/curator-framework-2.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.7.1
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.7.1
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.12.0
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.12.0/curator-recipes-2.12.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.12.0
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.12.0/curator-recipes-2.12.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.6.0
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.6.0/curator-recipes-2.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.6.0
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.6.0/curator-recipes-2.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.7.1
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.7.1
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.12.0
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.12.0/curator-test-2.12.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.12.0
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.12.0/curator-test-2.12.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.6.0
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.6.0/curator-test-2.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.6.0
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.6.0/curator-test-2.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.7.1
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.7.1/curator-test-2.7.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.7.1
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.7.1/curator-test-2.7.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.7.1
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.7.1/curator-test-2.7.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.7.1
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.7.1/curator-test-2.7.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/curator/apache-curator/2.12.0/apache-curator-2.12.0.pom
/usr/share/java/.m2/repository/org/apache/curator/apache-curator/2.6.0/apache-curator-2.6.0.pom
/usr/share/java/.m2/repository/org/apache/curator/apache-curator/2.7.1/apache-curator-2.7.1.pom
/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.12.0/curator-client-2.12.0.jar
/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.12.0/curator-client-2.12.0.pom
/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.6.0/curator-client-2.6.0.jar
/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.6.0/curator-client-2.6.0.pom
/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.jar
/usr/share/java/.m2/repository/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.pom
/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.12.0/curator-framework-2.12.0.jar
/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.12.0/curator-framework-2.12.0.pom
/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.6.0/curator-framework-2.6.0.jar
/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.6.0/curator-framework-2.6.0.pom
/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.jar
/usr/share/java/.m2/repository/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.pom
/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.12.0/curator-recipes-2.12.0.jar
/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.12.0/curator-recipes-2.12.0.pom
/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.6.0/curator-recipes-2.6.0.jar
/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.6.0/curator-recipes-2.6.0.pom
/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.jar
/usr/share/java/.m2/repository/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.pom
/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.12.0/curator-test-2.12.0.jar
/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.12.0/curator-test-2.12.0.pom
/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.6.0/curator-test-2.6.0.jar
/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.6.0/curator-test-2.6.0.pom
/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.7.1/curator-test-2.7.1.jar
/usr/share/java/.m2/repository/org/apache/curator/curator-test/2.7.1/curator-test-2.7.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-curator/LICENSE
/usr/share/package-licenses/mvn-curator/curator-client_LICENSE
/usr/share/package-licenses/mvn-curator/curator-examples_LICENSE
/usr/share/package-licenses/mvn-curator/curator-framework_LICENSE
/usr/share/package-licenses/mvn-curator/curator-recipes_LICENSE
/usr/share/package-licenses/mvn-curator/curator-test_LICENSE
/usr/share/package-licenses/mvn-curator/curator-x-discovery-server_LICENSE
/usr/share/package-licenses/mvn-curator/curator-x-discovery_LICENSE
